# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Bethany Corcoran's Links"

# Avatar image path
avatar: "./images/goblinhappy.png"

# Name section text
name: "Bethany Corcoran"

# Tagline section text
tagline: >-
    she/her - I also go by Fneb.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-youtube"
      text: "Fneb on YouTube"
      url: "https://www.youtube.com/fneb"
      alt: "Fneb on YouTube"
      title: "Fneb on YouTube"
      target: "_blank"
  - link:
      icon: "fa-solid fa-cubes"
      text: "Fneb on Printables"
      url: "https://www.printables.com/@fneb"
      alt: "Fneb on Printables"
      title: "Fneb on Printables"
      target: "_blank"
  - link:
      icon: "fa-brands fa-twitch"
      text: "Fneb on Twitch"
      url: "https://www.twitch.tv/fneb"
      alt: "Fneb on Twitch"
      title: "Fneb on Twitch"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "Fneb Live Archive <span class='link-button-text'>Twitch VODs uploaded here</span>"
      url: "https://www.youtube.com/@FnebLiveArchive"
      alt: "Fneb Live Archive"
      title: "Fneb Live Archive"
      target: "_blank"
  - link:
      icon: "fa-solid fa-podcast"
      text: "This Isn't Working: Exploring and Facing how our Lives are Going"
      url: "https://podcasters.spotify.com/pod/show/this-isnt-working-podcast"
      alt: "This Isn't Working: Exploring and Facing how our Lives are Going. A podcast I do with a friend"
      title: "This Isn't Working: Exploring and Facing how our Lives are Going. A podcast I do with a friend"
      target: "_blank"
  - link:
      icon: "fa-brands fa-markdown"
      text: "My rarely-used blog"
      url: "https://www.bethanycorcoran.co.uk"
      alt: "My rarely-used blog"
      title: "My rarely-used blog"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame


# Footer text
footer: >
    Hi how are you today?

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  Design © 2026  <a href="https://link.zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
